name: build AMI

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Packer
      run: |
        sudo apt-get update
        sudo apt-get install -y packer

    - name: Add required plugins
      run: packer init packer/jenkins-ami.pkr.hcl

    - name: Validate Packer template
      run: | 
        packer validate  \
        -var 'aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}' \
        -var 'aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
        -var 'region=${{ secrets.AWS_REGION }}' \
        -var 'source_ami=${{ secrets.SOURCE_AMI}}' \
        packer/jenkins-ami.pkr.hcl

    - name: packer build template
      run: | 
        packer build  \
        -var 'aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}' \
        -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
        -var 'region=${{ secrets.AWS_REGION }}' \
        -var 'source_ami=${{ secrets.SOURCE_AMI}}' \
        packer/jenkins-ami.pkr.hcl