name: build Jenkins AMI

on:
  pull_request:
    branches:
      - main

jobs:
  build_packer_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Packer
      run: |
        sudo apt-get update
        sudo apt-get install -y packer

    - name: Packer Validate
      run: |
        cd packer/
        packer init jenkins-ami.pkr.hcl
        packer validate -var JENKINS_ADMIN_USERNAME=${{ secrets.JENKINS_ADMIN_USERNAME }} -var JENKINS_ADMIN_PASSWORD=${{ secrets.JENKINS_ADMIN_PASSWORD }} -var source_ami=${{ secrets.SOURCE_AMI }} jenkins-ami.pkr.hcl

    - name: Packer Build
      run: |
        cd packer/
        packer build -var JENKINS_ADMIN_USERNAME=${{ secrets.JENKINS_ADMIN_USERNAME }} -var JENKINS_ADMIN_PASSWORD=${{ secrets.JENKINS_ADMIN_PASSWORD }} -var source_ami=${{ secrets.SOURCE_AMI }} jenkins-ami.pkr.hcl
